# Generated by Django 2.1.5 on 2019-02-08 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('complete', 'Complete')], default='pending', max_length=96)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=96, null=True)),
                ('cover_art', models.CharField(max_length=1028, null=True)),
                ('description', models.TextField(null=True)),
                ('aggregate_rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_platform_id', models.IntegerField()),
                ('platform_name', models.CharField(max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('out', 'Checked Out'), ('in', 'Checked In')], default='in', max_length=96)),
                ('checked_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_checkout_user', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_game', to='gl_library.Game')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_owner', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_platform', to='gl_library.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='gl_library.Platform'),
        ),
        migrations.AddField(
            model_name='borrowevent',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_game', to='gl_library.UserGameCopy'),
        ),
    ]
