# Generated by Django 2.1.5 on 2019-02-05 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('title', models.CharField(max_length=96)),
                ('cover_art', models.CharField(max_length=1028)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('out', 'Checked Out'), ('in', 'Checked In')], default='in', max_length=96)),
                ('checked_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out_user', models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_checkout_user', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_game', to='gl_library.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
