# Generated by Django 2.1.5 on 2019-02-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowevent',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowevent',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_game', to='gl_library.UserGameCopy'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_art',
            field=models.CharField(max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='usergamecopy',
            name='checked_out_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_checkout_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergamecopy',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_game', to='gl_library.Game'),
        ),
        migrations.AlterField(
            model_name='usergamecopy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_statuses_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
