# Generated by Django 2.1.5 on 2019-02-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='gl_library.Platform'),
        ),
    ]
