# Generated by Django 2.1.5 on 2019-02-06 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='GameStatus',
            new_name='UserGameCopy',
        ),
    ]
