# Generated by Django 2.1.5 on 2019-02-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl_library', '0003_auto_20190206_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
